const verbList = [
  "Sein",
  "Haben",
  "Werden",
  "Können",
  "Müssen",
  "Sagen",
  "Machen",
  "Geben",
  "Kommen",
  "Sollen",
  "Wollen",
  "Gehen",
  "Wissen",
  "Sehen",
  "Lassen",
  "Stehen",
  "Finden",
  "Bleiben",
  "Liegen",
  "Heißen",
  "Denken",
  "Nehmen",
  "Tun",
  "Dürfen",
  "Glauben",
  "Halten",
  "Nennen",
  "Mögen",
  "Zeigen",
  "Führen",
  "Sprechen",
  "Bringen",
  "Leben",
  "Fahren",
  "Meinen",
  "Fragen",
  "Kennen",
  "Gelten",
  "Stellen",
  "Spielen",
  "Arbeiten",
  "Brauchen",
  "Folgen",
  "Lernen",
  "Bestehen",
  "Verstehen",
  "Setzen",
  "Bekommen",
  "Beginnen",
  "Erzählen",
  "Versuchen",
  "Schreiben",
  "Laufen",
  "Erklären",
  "Entscheiden",
  "Erleben",
  "Laufen",
  "Treffen",
  "Warten",
  "Lesen",
  "Verlieren",
  "Schlafen",
  "Ziehen",
  "Arbeiten",
  "Sprechen",
  "Wohnen",
  "Gehören",
  "Erreichen",
  "Tragen",
  "Treiben",
  "Öffnen",
  "Schließen",
  "Vergessen",
  "Gewinnen",
  "Liegen",
  "Beginnen",
  "Bestehen",
  "Stellen",
  "Finden",
  "Kommen",
  "Halten",
  "Denken",
  "Machen",
  "Sehen",
  "Geben",
  "Nehmen",
  "Sollen",
  "Wollen",
  "Können",
  "Müssen",
  "Lassen",
  "Stehen",
  "Bleiben",
  "Finden",
  "Heißen",
  "Denken",
  "Nehmen",
  "Tun",
  "Dürfen",
  "Glauben",
  "Halten",
  "Nennen",
  "Abfahren", "Abgeben", "Abholen", "Abschicken", "Abschließen", "Absehen", "Abstimmen", "Abwaschen", "Anbieten", "Anfangen",
  "Ankommen", "Anmelden", "Anrufen", "Ansehen", "Anstellen", "Anwenden", "Arbeiten", "Aufbauen", "Aufdrehen", "Aufessen",
  "Aufgeben", "Aufhören", "Aufladen", "Aufräumen", "Aufstehen", "Ausbilden", "Ausfüllen", "Ausgehen", "Aushalten", "Ausleihen",
  "Auspacken", "Ausprobieren", "Ausruhen", "Aussehen", "Aussteigen", "Auswählen", "Basteln", "Befehlen", "Begleiten", "Behaupten",
  "Behandeln", "Beheben", "Beitreten", "Bekämpfen", "Bekennen", "Belohnen", "Benutzen", "Beraten", "Berechnen", "Bereiten",
  "Beseitigen", "Besichtigen", "Besitzen", "Bestellen", "Besuchen", "Betrügen", "Beurteilen", "Bewegen", "Beweisen", "Bezahlen",
  "Danken", "Dauern", "Deckeln", "Dehnen", "Dienen", "Einbauen", "Einfallen", "Einfrieren", "Eingeben", "Einladen",
  "Einpacken", "Einrichten", "Einschalten", "Einschließen", "Einsteigen", "Eintragen", "Einwandern", "Erarbeiten", "Erfahren", "Erfinden",
  "Erfüllen", "Erhalten", "Erkennen", "Erklären", "Erlauben", "Erleben", "Erreichen", "Ersetzen", "Erziehen", "Fangen",
  "Feiern", "Fernsehen", "Festhalten", "Finden", "Fliegen", "Fließen", "Folgen", "Fordern", "Fördern", "Fragen",
  "Fressen", "Frieren", "Fühlen", "Führen", "Geben", "Gelingen", "Genießen", "Geben", "Glauben", "Greifen"
];

export default verbList;